server.port: 8080

huasu:
  ip: 118.31.40.61
  weixin:
    auth2:
      appid: wx33fcd264b461fb30
      secret: f22d4666bd441d09a744ce1b565adf7d

spring:
  datasource:
    url: jdbc:MySQL://${huasu.ip}:3306/huasuManager?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: huasu2017
    driver-class-name: com.mysql.jdbc.Driver
  http.encoding.force: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  redis.password: 123456

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true

#logging.level.root: debug